<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DKK5M0P" failures="2" tests="2" name="ErrorValidation" time="12.207" errors="0" timestamp="2025-02-06T19:31:53 IST">
  <testcase classname="tests.ErrorValidation" name="loginNegativeCheck" time="1.236">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at tests.ErrorValidation.loginNegativeCheck(ErrorValidation.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginNegativeCheck -->
  <testcase classname="tests.ErrorValidation" name="loginNegativeCheck" time="11.784">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at testComponents.BaseTest.getScreenshot(BaseTest.java:85)
at testComponents.Listeners.onTestFailure(Listeners.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginNegativeCheck -->
</testsuite> <!-- ErrorValidation -->
